# Generated by Django 3.2.8 on 2021-10-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
